version: '3.8'

services:
  helper:
    build: .
    container_name: helper
    restart: always
    ports:
      - "4000:4000"
    networks:
      - app_network
    
  jenkins:
    build: .  # Utilise le Dockerfile pour construire l'image
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - app_network
    
    
networks:
  app_network:
    driver: bridge

volumes:
  jenkins_home:  
