version: '3.8'

services:
  helper:
    build: .
    container_name: helper
    restart: always
    ports:
      - "4000:4000"
    networks:
      - app_network
    
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080" 
      - "50000:50000" 
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./plugins.txt:/usr/share/jenkins/ref/plugins.txt 
      - /var/run/docker.sock:/var/run/docker.sock  
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # Optional to skip the setup wizard
    networks:
      - app_network
    
    
networks:
  app_network:
    driver: bridge

volumes:
  jenkins_home:  
